### ISSUE TITLE
An error when run the "python generate_optim_largescene.py configs/pointcloud_crop/demo_matterport.yaml"

### ISSUE THREAD

**Issue by comeonccc** [tangjiapeng/SA-ConvONet#12]
您好，我按照ReadMe.txt的指引，新建了conda环境，并运行了setup指令。然后，在运行python generate_optim_largescene.py configs/pointcloud_crop/demo_matterport.yaml时出现了报错，具体内容为：“Cannot import name KDTree”，我是在unbutu20.04的终端内运行的该程序，请问我应该怎么解决这个错误呢？非常感谢！

**Comment by Zhong0501** [comment]
Windows执行这一步也发生错误了，错误如下，求解决
(sa_conet) D:\CodeField\Python\GitHub\SA-ConvONet>python generate_optim_largescene.py configs/pointcloud_crop/demo_matterport.yaml
test_split: test
D:/CodeField/Python/GitHub/SA-ConvONet/out/demo_matterport/room_grid64.pt
=> Loading checkpoint from local file...
Warning: generator does not support pointcloud generation.
  0%|                                                                                                                                                       | 0/2 [00:00<?, ?it/s]D:/CodeField/Python/GitHub/SA-ConvONet/out/demo_matterport/room_grid64.pt
=> Loading checkpoint from local file...
Process scenes in a sliding-window manner
ft only encoder True
only optimize encoder█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2499/2499 [15:38<00:00,  4.74it/s] 
Traceback (most recent call last):
  File "generate_optim_largescene.py", line 253, in <module>
    loss = trainer.sign_agnostic_optim_cropscene_step(crop_data, state_dict)
  File "D:\CodeField\Python\GitHub\SA-ConvONet\src\conv_onet\training.py", line 216, in sign_agnostic_optim_cropscene_step
    loss = self.compute_sign_agnostic_cropscene_loss(data)
  File "D:\CodeField\Python\GitHub\SA-ConvONet\src\conv_onet\training.py", line 244, in compute_sign_agnostic_cropscene_loss
    c = self.model.encode_inputs(inputs)
  File "D:\CodeField\Python\GitHub\SA-ConvONet\src\conv_onet\models\__init__.py", line 60, in encode_inputs
    c = self.encoder(inputs)
  File "D:\27239\App\Anaconda3\envs\sa_conet\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\CodeField\Python\GitHub\SA-ConvONet\src\encoder\pointnet.py", line 299, in forward
    pooled = self.pool_local(index, net)
  File "D:\CodeField\Python\GitHub\SA-ConvONet\src\encoder\pointnet.py", line 274, in pool_local
    fea = self.scatter(c.permute(0, 2, 1), index[key])
RuntimeError: expected scalar type Long but found Int
The abo
